version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: dikantek_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dikantek_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: dikantek_redis
    ports:
      - "6379:6379"

volumes:
  postgres_data:
    driver: local